spring.application.name=ticket-order-api
ticket-order-platform.cors.allowed-origins=http://localhost:5173
ticket-order-platform.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
ticket-order-platform.cors.allowed-headers=*
ticket-order-platform.cors.allow-credentials=false
ticket-order-platform.cors.max-age=3600
