apiVersion: v1
kind: Service
metadata:
  name: ticket-order-postgres
  labels:
    app.kubernetes.io/name: ticket-order-postgres
    app.kubernetes.io/part-of: ticket-order-platform
spec:
  selector:
    app.kubernetes.io/name: ticket-order-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
