apiVersion: v1
kind: Secret
metadata:
  name: ticket-order-postgres
  labels:
    app.kubernetes.io/part-of: ticket-order-platform
type: Opaque
stringData:
  username: ticket_order
  password: ticket_order
