EventEntity.findByStatus=\
SELECT DISTINCT event \
FROM EventEntity event \
LEFT JOIN FETCH event.details \
LEFT JOIN FETCH event.orders \
WHERE event.status = ?1

EventEntity.findByOwnerId=\
SELECT DISTINCT event \
FROM EventEntity event \
LEFT JOIN FETCH event.details \
LEFT JOIN FETCH event.orders \
WHERE event.ownerId = ?1

EventOrderEntity.findByCustomerId=\
SELECT eventOrder \
FROM EventOrderEntity eventOrder \
JOIN FETCH eventOrder.event \
WHERE eventOrder.customerId = ?1

UserEntity.findByEmail=\
SELECT u \
FROM UserEntity u \
WHERE u.email = ?1
