EventEntity.findByStatus=\
SELECT DISTINCT event \
FROM EventEntity event \
LEFT JOIN FETCH event.details \
WHERE event.status = ?1

EventEntity.findByOwnerId=\
SELECT DISTINCT event \
FROM EventEntity event \
LEFT JOIN FETCH event.details \
WHERE event.ownerId = ?1

EventEntity.findByIdWithOrders=\
SELECT DISTINCT event \
FROM EventEntity event \
LEFT JOIN FETCH event.details \
LEFT JOIN FETCH event.orders \
WHERE event.id = ?1

EventOrderEntity.findUpcomingByCustomerId=\
SELECT eventOrder \
FROM EventOrderEntity eventOrder \
JOIN FETCH eventOrder.event event \
WHERE eventOrder.customerId = ?1 \
AND event.date >= ?2

EventOrderEntity.findByEventIdsOrderBySeatPosition=\
SELECT eventOrder \
FROM EventOrderEntity eventOrder \
JOIN FETCH eventOrder.event event \
WHERE event.id IN ?1 \
ORDER BY eventOrder.rowNumber ASC, eventOrder.placeNumber ASC
