apiVersion: v1
kind: Service
metadata:
  name: ticket-order-api
  labels:
    app.kubernetes.io/name: ticket-order-api
    app.kubernetes.io/part-of: ticket-order-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ticket-order-api
  ports:
    - name: http
      port: 8080
      targetPort: http
